# Generated by Django 5.0.6 on 2024-06-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationcodemodel',
            name='verification_code',
        ),
        migrations.AddField(
            model_name='verificationcodemodel',
            name='code',
            field=models.CharField(default=0, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
